postcode: "SW1A 1AA"  # London example

thresholds:
  temperature:
    min: 0         # Alert if temp falls below 0°C
    max: 30        # Alert if temp rises above 30°C
  rain_chance: 70   # Alert if rain chance exceeds 70%
  uv_index: 7       # Alert if UV index is 7 or higher
  pollen: # individual thresholds for different levels of pollen per grass, tree and weed
    grass_pollen_threshold:
      low: 30
      medium: 50
    tree_pollen_threshold:
      low: 30
      medium: 60
    weed_pollen_threshold:
      low: 40
      medium: 60
discord:
  webhook_url: "https://discord.com/api/webhooks/xxxx/yyyy"
