postcode: "SW1A 1AA"  # London example

thresholds:
  temperature:
    cold: 6
    hot: 19
    extreme: 29
  precipitation_amount: 5
  uv_index: 6
  medium_wind: 47
  high_wind: 64
  gust: 50
  strong_gust: 60
  extreme_gust: 70
  pollen:
    grass:
      low: 30
      medium: 60
    tree:
      low: 15
      medium: 90
    weed:
      low: 10
      medium: 50
discord:
  webhook_url: "https://discord.com/api/webhooks/xxxx/yyyy"
